# Generated by Django 5.0.7 on 2024-08-07 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_on',)},
        ),
    ]
