# Generated by Django 5.0.7 on 2024-09-12 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_postmodel_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogProfile',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
