# Generated by Django 5.0.7 on 2024-09-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_delete_blogprofile_delete_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('dated_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-dated_on',),
            },
        ),
    ]
