# Generated by Django 5.0.7 on 2024-09-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_articlepostmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepostmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
