# Generated by Django 5.0.7 on 2024-09-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_articlepostmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepostmodel',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
