# Generated by Django 5.0.7 on 2024-09-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_articlepostmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepostmodel',
            name='article_content',
            field=models.TextField(null=True),
        ),
    ]
