# Generated by Django 5.0.7 on 2024-09-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_articlepostmodel_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepostmodel',
            name='sub_title',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
